### ISSUE TITLE
Type check on Include in stores?

### ISSUE THREAD

**Issue by aljachimiak** [oddnetworks/oddworks#161]
While putting together some tests for `?include=entities`, I got tripped up by the type needed for `args.include`.  [As seen here.](https://github.com/oddnetworks/oddworks/blob/master/lib/stores/redis/index.js#L296) 

## Expected Behavior

My error was using a string like `arge.include = 'entities'`.

[If you look here](https://github.com/oddnetworks/oddworks/blob/master/lib/stores/redis/index.js#L273-L278), we do type checking on `channel` and `id`.

I guess we should expect a helpful error message is the wrong type is passed.

## Current Behavior

Currently, if `typeof(args.include) === 'string'`, we continue silently on our way ignoring the attempt at fetching the included relationships.  We successfully return the collection that was requested, however, it does not include `body.included`.

## Possible Solution

I suggest doing a similar check on `args.include` before hitting [this block](https://github.com/oddnetworks/oddworks/blob/master/lib/stores/redis/index.js#L296).

Perhaps something like:
````javascript
if (!_.isArray(include)) {
    return Promise.reject(new Error('args.include must be an array.'));
}
````

**Comment by aljachimiak** [comment]
I'm happy to jump on this...

My guess is that it would need to be done in all stores.

**Comment by blainsmith** [comment]
That makes sense. It should get turned into an array before that since `?include=entities,anotherRelationship` is valid in the URL.

This would need to be changed in all stores and its not always required too.

If you are working on tests for this and are in the head space for it you are welcome to jump on it. I will be available for you if you have any questions about store functions too.
