### ISSUE TITLE
Login, Watch List, Play State, OH MY!

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#223]
I will be tackling the following routes soon so SDKs and app can track viewer state. I wanted to publicly document this so that others can prepare for it.
## Viewer

``` json
{
  "data": {
    "id": "some-user-id",
    "type": "viewer",
    "attributes": {
      "channel": "odd-networks",
      "active": true,
      "entitlements": ["yearly", "gold"]
    },
    "relationships": {
      "platforms": {
        "data": [
          {"id": "apple-ios", "type": "platform"},
          {"id": "roku", "type": "platform"}
        ]
      },
      "watchlist": {
        "data": [
          {"id": "game-of-thrones-s1", "type": "collection"},
          {"id": "fido", "type": "video"}
        ]
      },
      "playstate": {
        "data": [
          {"id": "fido", "type": "video", "meta": {"progress": 4322132}},
          {"id": "game-of-thrones-s1-e4", "type": "video", "meta": {"progress": 3221}}
        ]
      }
    }
  }
}
```
## `POST|PATCH /viewers/:id/relationships/watchlist`

Update the viewer watch list with the video or collection they chose.
### Request Payload

``` json
{
  "data": [
    {"id": "game-of-thrones-season-1", "type": "collection"},
    {"id": "fido", "type": "video"}
  ]
}
```
## `POST|PATCH /viewers/:id/relationships/playstate`

Update the viewer play state for video progress.
### Request Payload

``` json
{
  "data": [
    {"id": "fido", "type": "video", "meta": {"progress": 32123}}
  ]
}
```
## `DELETE /viewers/:id/relationships/watchlist`

Remove a resource from the watch list.
### Request Payload

``` json
{
  "data": [
    {"id": "fido", "type": "collection"},
    {"id": "fido", "type": "collection"}
  ]
}
```
## `DELETE /viewers/:id/relationships/playstate`

Remove a resource from the play state.
### Request Payload

``` json
{
  "data": [
    {"id": "fido", "type": "video"}
  ]
}
```

**Comment by brkattk** [comment]
I think due to http://discuss.jsonapi.org/t/metadata-about-relationships/86/4 we'll have to do the following for progress (aka playstate)

### `progress` Resource

**Attributes**

- `videoId` - String
- `channelId` - String
- `viewerId` - String
- `position` - Integer - position in milliseconds
- `complete` - Boolean - optional (default to false)

### POST /progress

Update a viewer's progress on a video.

**Request Payload**
```json
{
  "data": {
    "type": "progress",
    "attributes": {
      "videoId": "id-of-video",
      "position": 1234,
      "complete": false
    }
  }
}
```
Internally we'll also add the `channelId` (might not be necessary) and `viewerId` attributes.

### PATCH /progress/:id

Update progress of a viewer within a video. 

Limit to only `position` and `complete` to be updatable.

**Request Payload**
```json
{
  "data": {
    "attributes": {
      "position": 4444
    }
  }
}
```

**Comment by brkattk** [comment]
^ This allows us to do something like `GET /video/:id?include=progress` to get the progress.
