### ISSUE TITLE
Cache all DB reads that occur in the lifecycle of a standard request

### ISSUE THREAD

**Issue by genexp** [oddnetworks/oddworks#4]
We need to defend better against increases in load.  At the moment, we're increasing our DB reads linearly in relation to the requests coming into the API.  

We should use a small LRU cache for device tokens, organization lookups, and and other data read from our operational database that are made repeatedly for each request.

This is one of the two big takeaways from tonights adventures.  The second is the Tinypass request timeouts.

CC: @tquackenbush @kixxauth

**Comment by kixxauth** [comment]
Yeah, at first I thought @genexp was suggesting Redis here, which would not help us since the application servers are getting bound by network activity (consuming both memory and cpu resources), and making requests to a redis cache has a very high network activity.

What he's actually suggesting is a caching mechanism in user/application memory with the actual server instance. I think this would be amazeballs.

The goal here to to see application server throughput go up, but database throughput stays behind. This will eliminate the network activity churn of doing database lookups.

**Comment by blainsmith** [comment]
LRU was added to our internal API. We can push this stuff out here as well.
