### ISSUE TITLE
Token Scopes

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#45]
With the introduction of writing data into the content server we should cover certain token scopes in order to provide some security, yet keep it simple enough for users to understand. Right now we only have one `platform` scope which is given out to platforms to request data from the server. In my opinion this should change to a `read` scope while we introduce a `write` scope for accepting data modification requests.

To give you an idea what a bigger service, like GitHub, offers here is a screenshot of their New Token page. We don't have nearly as much security concerns, but we should consider some basic scopes to protect aspects of the server.

![screen shot 2016-05-02 at 1 50 32 pm](https://cloud.githubusercontent.com/assets/483829/14962575/87038120-106d-11e6-819d-c734cfd89b68.png)

**Proposed Scopes**

`read` and `write` scopes should cover the majority of use cases when someone stands up the Oddworks server. 

So most of the time developers would be given tokens with `read` access since they are really just consuming content, but in some case a developer could be given one with `read` and `write` if apps ever needed to write data back.

If anyone has any other ideas let me know. I am using this to do the work for the ingestion part of saving channel and platform data.

**Comment by barthdamon** [comment]
Great idea. I ran into these concerns when I started using the push notification service. Would be much safer to check for the tokens read/write privileges. Token scopes would then be attached to the request just like all the rest of the org info correct?

**Comment by blainsmith** [comment]
Yes. Tokens would have specific scopes to be able to hit certain API routes. We just need to define what those scopes allow you to do on the API. If 2 are not enough then propose more.

**Comment by brkattk** [comment]
Talked with @blainsmith this morning and got thinking about scopes:

- platform-dependent read-only for catalog/config
- platform-independent write-only config
- platform-independent read-only config
- platform-independent read-only catalog
- platform-independent write-only catalog

I think any combination of those would handle the various use cases we have for:

- devices accessing content
- sync service
- push notification service
- manipulating push notifications via dashboard
- manipulating catalog via dashboard

Trying to think of any other specific use cases we might have and how we'd want to limit their access to the rest of the data.

**Comment by blainsmith** [comment]
Technically everything has a platform. Since we renamed it to platform we can now have 'WEB' or anything else too.

I was thinking and perhaps we should not include the service name in the scope since in theory a service should be able to be added to Oddworks without needed to re-issue tokens.

**Comment by kixxauth** [comment]
__Implemented like this in v3:__

Oddworks is designed to support authentication to a service using [JSON Web Tokens](https://jwt.io/introduction/) (JWTs). A decoded Oddworks JWT will take 1 of 3 forms:

Admin
```js
iss: 'STRING options.jwtIssuer',
sub: 'USER DEFINED STRING',
aud: ['admin', 'platform']
```

Platform, no user
```js
iss: 'STRING options.jwtIssuer',
aud: ['platform'],
channel: 'STRING - channel id',
platform: 'STRING - platform id'
```

Platform, with user
```js
iss: 'STRING options.jwtIssuer',
aud: ['platform'],
channel: 'STRING - channel id',
platform: 'STRING - platform id',
user: 'STRING - user.id'
```

An important consideration is that the Oddworks library can support two "servers": One for the consumer devices to access and consume content, and another admin "backend" API for server side tools to configure and update the content. In most cases, both of these concerns will be mixed on the same server instance, so there is some care taken to make sure that requests are authenticated and authorized properly.

The two types of services (consumer and admin) are represented on a JWT the audience member (`.aud`). This property is an array of strings representing the audiences for which the caller has access rights for. The audience strings supported by Oddworks out of the box are:

* 'platform' - The consumer facing API accessed by devices to consume content.
* 'admin' - The backend API accessed by other machines to configure content.

Notice that platform consumer JWTs do not have a subject (`.sub`) member. This is because the combined channel, platform and user IDs compose the subject, so we don't want to mix concerns.

### Authenticating Middleware
The authenticate middlware is constructed using

    bus.query({middleware: 'authenticate'}, OPTIONS)

It is expected that the encoded JWT string is sent to the server on the Authorization header by default:

    "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJh..."

Other headers can be used instead by setting the `options.header` String when constructing the authenticate middleware with `bus.query({middleware: 'authenticate'}, OPTIONS)`.

The authenticate middleware parses the header, then calls

    bus.query({role: 'identity', cmd: 'verify'}, {token})

to parse and verify the token. This returns an Object from the identity service:

```js
{
    audience: ['platform'], // The audience Array
    channel: channel, // The Channel resource
    platform: platform, // The Platform resource
    user: user // The User resource
}
```

This "identity" Object is assigned to the request as `req.identity` for use in middleware and route handlers. This is important because it allows other parts of the request/response cycle to fetch, configure and decorate the response without having to fetch fresh copies of the audience, channel, platform or user objects.

### Authorizing Middleware
The authorizing middlware is constructed using

    bus.query({middleware: 'authorize'}, OPTIONS)

It is expected that the request has already passed through the authenticating middleware and the `req.identity` Object is present. The authenticating middleware then checks to see if the requested HTTP method can be called by members of the given audience(s) on the assigned route.
