### ISSUE TITLE
Deprecate X-Access-Token Header for Authorization Header Only

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#83]
Always use `Authorization: Bearer JWT` header format for sending requests for both user based and non-user based requests.

## Expected Behavior
When a platform ships they SDK has a JWT set with just the `channel` and `platform` defined in its payload. When a user logs in and is authenticated Oddworks should send the platform back a new JWT with the same `channel`, `platform`, and now a `user` set to identify it as an authorized user. The SDK would use the new JWT for all future requests.

Shipped JWT Payload: `{channel: 'odd', platform: 'roku'}`
Authenticated JWT Payload: `{channel: 'odd', platform: 'roku', user: 13}`

## Current Behavior
Because of an old caching configuration a custom `X-Access-Token` was used for the JWT that was shipped with the device. Then once a user authenticated the SDK would sent a 2nd JWT in the `Authorization` header requiring Oddworks to decode both of them.

**Comment by kixxauth** [comment]
__Implemented in V3__

Oddworks is designed to support authentication to a service using [JSON Web Tokens](https://jwt.io/introduction/) (JWTs). A decoded Oddworks JWT will take 1 of 3 forms:

Admin
```js
iss: 'STRING options.jwtIssuer',
sub: 'USER DEFINED STRING',
aud: ['admin', 'platform']
```

Platform, no user
```js
iss: 'STRING options.jwtIssuer',
aud: ['platform'],
channel: 'STRING - channel id',
platform: 'STRING - platform id'
```

Platform, with user
```js
iss: 'STRING options.jwtIssuer',
aud: ['platform'],
channel: 'STRING - channel id',
platform: 'STRING - platform id',
user: 'STRING - user.id'
```

An important consideration is that the Oddworks library can support two "servers": One for the consumer devices to access and consume content, and another admin "backend" API for server side tools to configure and update the content. In most cases, both of these concerns will be mixed on the same server instance, so there is some care taken to make sure that requests are authenticated and authorized properly.

The two types of services (consumer and admin) are represented on a JWT the audience member (`.aud`). This property is an array of strings representing the audiences for which the caller has access rights for. The audience strings supported by Oddworks out of the box are:

* 'platform' - The consumer facing API accessed by devices to consume content.
* 'admin' - The backend API accessed by other machines to configure content.

Notice that platform consumer JWTs do not have a subject (`.sub`) member. This is because the combined channel, platform and user IDs compose the subject, so we don't want to mix concerns.

### Authenticating Middleware
The authenticate middlware is constructed using

    bus.query({middleware: 'authenticate'}, OPTIONS)

It is expected that the encoded JWT string is sent to the server on the Authorization header by default:

    "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJh..."

Other headers can be used instead by setting the `options.header` String when constructing the authenticate middleware with `bus.query({middleware: 'authenticate'}, OPTIONS)`.

The authenticate middleware parses the header, then calls

    bus.query({role: 'identity', cmd: 'verify'}, {token})

to parse and verify the token. This returns an Object from the identity service:

```js
{
    audience: ['platform'], // The audience Array
    channel: channel, // The Channel resource
    platform: platform, // The Platform resource
    user: user // The User resource
}
```

This "identity" Object is assigned to the request as `req.identity` for use in middleware and route handlers. This is important because it allows other parts of the request/response cycle to fetch, configure and decorate the response without having to fetch fresh copies of the audience, channel, platform or user objects.

### Authorizing Middleware
The authorizing middlware is constructed using

    bus.query({middleware: 'authorize'}, OPTIONS)

It is expected that the request has already passed through the authenticating middleware and the `req.identity` Object is present. The authenticating middleware then checks to see if the requested HTTP method can be called by members of the given audience(s) on the assigned route.
